In [36]:
import numpy as np
import cv2
import glob
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os
#%matplotlib qt
%matplotlib inline


z = np.array([0,0,0], float)

b = np.array([2.55970773e-04], float)

c = np.append(z,b)

d = np.array([2.55970773e-04, -4.78875257e-01,  4.76967994e+02], float)

ave = np.add(z,d)

print("ave is", ave)


print(b)

print(x)

print(c)

objp = np.zeros((1,3), np.float32)

np.append(objp, [2.55970773e-04, -4.78875257e-01,  4.76967994e+02])



a_list = []

a_list.append(x)

a_list.append(b)

a_list.append(d)

print("a_list", a_list)

tmp = a_list.pop(0)

print("tmp is", tmp)

print("after pop, a_list is ", a_list)

end = a_list.pop()

print("end is", end)


z=d

print("z is now",z)


x1 = 264.9835914694545

x_list = []

x_list.append(x1)

x2 = x1/2

x_list2 = []

x_list2.append(x2)

print(x_list2)



x2 = 264.9835914694545
x_list3 = []
x_list3.append(x2)

print(x_list3)

c=x_list3.pop()

print(int(c))


z_array = np.zeros_like(ave)
z_array = np.add(z_array, ave)
print(z_array)


ave is [ 2.55970773e-04 -4.78875257e-01  4.76967994e+02]
[0.00025597]
[1. 2. 3.]
[0.         0.         0.         0.00025597]
a_list [array([1., 2., 3.]), array([0.00025597]), array([ 2.55970773e-04, -4.78875257e-01,  4.76967994e+02])]
tmp is [1. 2. 3.]
after pop, a_list is  [array([0.00025597]), array([ 2.55970773e-04, -4.78875257e-01,  4.76967994e+02])]
end is [ 2.55970773e-04 -4.78875257e-01  4.76967994e+02]
z is now [ 2.55970773e-04 -4.78875257e-01  4.76967994e+02]
[132.49179573472725]
[264.9835914694545]
264
[ 2.55970773e-04 -4.78875257e-01  4.76967994e+02]
